enum HTTPStatusCodes {
    OK_STATUS = 200,
    RESOURCE_CREATED = 201,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    UNPROCESSABLE_ENTITY = 422,
    INTERNAL_SERVER_ERROR = 500,
}

export {HTTPStatusCodes}
